# Generated by Django 5.2.5 on 2025-08-28 02:18

import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=32, unique=True)),
                ('currency', models.CharField(choices=[('KRW', 'KRW'), ('USD', 'USD')], default='KRW', max_length=3)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('status', models.CharField(default='ACTIVE', max_length=16)),
                ('version', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tx_type', models.CharField(choices=[('DEPOSIT', 'DEPOSIT'), ('WITHDRAW', 'WITHDRAW'), ('TRANSFER_OUT', 'TRANSFER_OUT'), ('TRANSFER_IN', 'TRANSFER_IN'), ('FEE', 'FEE'), ('REVERSAL', 'REVERSAL')], max_length=16)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('running_balance', models.DecimalField(decimal_places=2, max_digits=20)),
                ('currency', models.CharField(choices=[('KRW', 'KRW'), ('USD', 'USD')], default='KRW', max_length=3)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('transfer_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('idempotency_key', models.CharField(blank=True, max_length=64, null=True)),
                ('external_ref', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
        ),
    ]
