# Generated by Django 5.2.5 on 2025-08-28 05:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transactionhistory',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='transactionhistory',
            name='counterparty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='counter_transactions', to='accounts.account'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['owner'], name='accounts_ac_owner_i_e99d96_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['number'], name='accounts_ac_number_92e5e2_idx'),
        ),
        migrations.AddIndex(
            model_name='transactionhistory',
            index=models.Index(fields=['account', '-occurred_at'], name='accounts_tr_account_f35b88_idx'),
        ),
        migrations.AddIndex(
            model_name='transactionhistory',
            index=models.Index(fields=['transfer_id'], name='accounts_tr_transfe_5383c2_idx'),
        ),
        migrations.AddConstraint(
            model_name='transactionhistory',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='amount_gt_zero'),
        ),
        migrations.AlterUniqueTogether(
            name='transactionhistory',
            unique_together={('account', 'idempotency_key')},
        ),
    ]
