repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 'v0.1.9'  # ruff 안정 버전
    hooks:
      - id: ruff
        args: [ --fix ]  # 자동 수정 가능한 것들은 수정
      - id: ruff-format  # ruff의 포맷터 (black 대신 사용 가능)

#  - repo: https://github.com/carloscuesta/gitmoji-cli
#    rev: 'v9.7.0'
#    hooks:
#      - id: gitmoji