[project]
name = "django-financial"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "django>=5.2.5",
]

[dependency-groups]
dev = [
    "djangorestframework>=3.16.1",
    "pytest>=8.4.1",
]
