# Generated by Django 5.2.5 on 2025-08-28 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_target', models.CharField(choices=[('INCOME', '수입'), ('EXPENSE', '지출')], max_length=10)),
                ('period_type', models.CharField(choices=[('DAILY', '일간'), ('WEEKLY', '주간'), ('MONTHLY', '월간'), ('YEARLY', '연간')], max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('result_image', models.ImageField(blank=True, null=True, upload_to='analysis_results/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
