# Generated by Django 5.2.5 on 2025-08-28 07:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Analysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "analysis_target",
                    models.CharField(
                        choices=[("INCOME", "수입"), ("EXPENSE", "지출")], max_length=10
                    ),
                ),
                (
                    "period_type",
                    models.CharField(
                        choices=[
                            ("DAILY", "일간"),
                            ("WEEKLY", "주간"),
                            ("MONTHLY", "월간"),
                            ("YEARLY", "연간"),
                        ],
                        max_length=10,
                    ),
                ),
                ("start_date", models.DateField(db_index=True)),
                ("end_date", models.DateField(db_index=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "result_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="analysis_results/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analyses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "user",
                            "analysis_target",
                            "period_type",
                            "start_date",
                            "end_date",
                        ),
                        name="unique_analysis",
                    )
                ],
            },
        ),
    ]
