# Generated by Django 5.2.5 on 2025-08-28 12:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analysis', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='analysis',
            constraint=models.UniqueConstraint(fields=('user', 'analysis_target', 'period_type', 'start_date', 'end_date'), name='unique_analysis'),
        ),
    ]
