<<<<<<< HEAD
# Generated by Django 5.2.5 on 2025-08-28 11:31
=======
# Generated by Django 5.2.5 on 2025-08-28 12:23
>>>>>>> develop

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

<<<<<<< HEAD
    dependencies = []
=======
    dependencies = [
    ]
>>>>>>> develop

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
<<<<<<< HEAD
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField()),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
=======
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
>>>>>>> develop
            ],
        ),
    ]
