<<<<<<< HEAD
# Generated by Django 5.2.5 on 2025-08-28 11:31
=======
# Generated by Django 5.2.5 on 2025-08-28 12:23
>>>>>>> develop

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        ("notification", "0001_initial"),
=======
        ('notification', '0001_initial'),
>>>>>>> develop
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
<<<<<<< HEAD
            model_name="notification",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to=settings.AUTH_USER_MODEL,
            ),
=======
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
>>>>>>> develop
        ),
    ]
