name: Deploy to EC2 via Docker Compose

on:
  push:
    branches:
      - ec2-damon

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy on EC2
        timeout-minutes: 10
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            set -e
            cd ~/app || { echo "❌ App directory not found"; exit 1; }

            echo "📥 Fetching latest code..."
            git fetch origin ec2-damon
            git checkout ec2-damon
            git pull origin ec2-damon

            echo "🐳 Restarting Docker Compose services..."
            docker-compose down
            docker-compose up -d --build

            echo "⏱️ Waiting for containers to start..."
            sleep 15

            echo "🌐 Reloading Nginx..."
            if command -v nginx >/dev/null 2>&1; then
              sudo nginx -t && sudo systemctl reload nginx || echo "⚠️ Nginx reload failed"
            fi

            echo "✅ Deployment completed successfully!"
          EOF

      - name: Post-deployment verification
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} \
            'cd ~/app && docker-compose ps && echo "✅ Verification completed"'